POST http://localhost:3000/user/newWorkorder/
content-type : application/json

{
    "workorder": {
        "buildingNumber" : "111",
        "apartmentNumber": "111",
        "loginTime": "$datetime '12-22-2019'",
        "completedTime": "$datetime '12-22-2019'",
        "sendTime": "$datetime '12-22-2019'", 
        "userId": "5cee87f8841e4c33f8636c09" 
    },
    "jobs" : [
        {
            "name": "Tv repair",
            "subCategory": "Tv",
            "room": "LivingRoom",
            "price": "23",
            "quantity": "2",
            "comment": "Comment about TV"
        },
        {
            "name": "Broken Window",
            "subCategory": "Windows",
            "room": "Hallway1",
            "price": 12,
            "quantity": 1,
            "comment": "Comment about Window in Hallway"
        }
    ],
    "user" : {
        "firstName": "John",
        "lastName": "Doe",
        "email": "mladenj@skydream.info",
        "emailPassword": "P0slednjiKr0jac"
    }
}